/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-1",
    "aws_cognito_identity_pool_id": "us-west-1:ff481857-75b0-4662-9327-8ef69eb9079f",
    "aws_cognito_region": "us-west-1",
    "aws_user_pools_id": "us-west-1_WeNsb9tEu",
    "aws_user_pools_web_client_id": "6fmsm3rifrmfpl0mcki19ohdtq",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "dropitfileupload110347-dev",
    "aws_user_files_s3_bucket_region": "us-west-1"
};


export default awsmobile;
